In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [9]:
d0=tf.ones((1,))
print(d0);
d0
d2=tf.ones((2,3))
d3=tf.ones([2,3,1,4])
print(d3.numpy());d3

tf.Tensor([1.], shape=(1,), dtype=float32)


In [15]:
import tensorflow as tf
from tensorflow import constant, ones, zeros, fill
a=constant([1,2,3,4],shape = [1,4],dtype=tf.int16);
print("a is \n", a);
b=constant(a,shape=[2,2],dtype = tf.int16)
c=ones([3,3]);c.shape
print(b,c)
tf.zeros_like(c)
d=zeros([4]);print(d);d
print(fill ([2,3],1));
print(ones([2,3]))
help(fill)

tf.Tensor(
[[10 10 10]
 [10 10 10]], shape=(2, 3), dtype=int32)


In [18]:
import tensorflow as tf
a0=tf.Variable([1,2,3,8], dtype = tf.float32)
a1=tf.Variable([1,2,3,8],dtype = tf.int32)
print(a0)
a1

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 8.], dtype=float32)>


<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 8], dtype=int32)>

In [21]:
from tensorflow import multiply, ones_like
#Define tensors
A1 = constant([1,2,3,4])
A23 = constant([[1,2,3],[1,6,4]])

#Define tensors to have correct shape
B1 = ones_like(A1)
B23 = ones_like(A23)

#Perform element-wise multiplication
C1 = multiply(A1,B1)
C2 = A1*B1
C23 = multiply(A23, B23)

print('\n C1: {}'.format(C1.numpy()))
print('\n C2:', A1*B1)
print('\n C23: {}'.format(C23.numpy()))


 C1: [1 2 3 4]

 C2: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)

 C23: [[1 2 3]
 [1 6 4]]


In [23]:
from tensorflow import reduce_sum
reduce_sum(fill([3,4,5],1),0)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]], dtype=int32)>

In [26]:
import tensorflow as tf
#E.g Gray image
gray0 = tf.random.uniform([2,2], maxval=255, dtype='int32')
gray=tf.reshape(gray0,[2*2,1])
tf.random.set_seed(123)
color0=tf.random.uniform([2,2,3], maxval=255, dtype='int32')
print(color0)
color = tf.reshape(color0,[2*2,3])
color

tf.Tensor(
[[[166 178 129]
  [ 68 163  75]]

 [[215  73  77]
  [ 97  41 189]]], shape=(2, 2, 3), dtype=int32)


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[166, 178, 129],
       [ 68, 163,  75],
       [215,  73,  77],
       [ 97,  41, 189]], dtype=int32)>